# Generated by Django 3.1.3 on 2021-02-04 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_sharing', '0002_filepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSharing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('permission', models.IntegerField(choices=[(0, 'ReadOnly'), (1, 'Read and Comment')], default=1)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_sharing.filepost')),
                ('shared_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
