# Generated by Django 3.1.3 on 2021-02-05 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('file_sharing', '0005_filecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecomment',
            name='comment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
