# Generated by Django 3.1.3 on 2021-02-05 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_sharing', '0006_filecomment_comment_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
